<a href="https://colab.research.google.com/github/rurusasu/Python/blob/develop/%E5%88%9D%E3%82%81%E3%81%A6%E3%81%AE%E3%82%A2%E3%83%A4%E3%83%A1%E5%88%86%E9%A1%9E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [0]:
# scilit-learnの様々な機能をimport
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC

In [0]:
# アヤメインスタンスを生成する
DataSet = load_iris()

In [8]:
# アヤメデータの中身を確認する
print("与えられたデータ")
print(DataSet.data)
print(DataSet.data.shape)
print('-----------------')
print('予測するデータ')
print(DataSet.target)
print(DataSet.target.shape)
print(DataSet.target_names)

与えられたデータ
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [12]:
# Pandasの定義
DataSet_data = pd.DataFrame(DataSet.data, columns=['がく片の長さ', 'がく片の幅', '花びらの長さ', 'はなびらの幅'])
DataSet_target = pd.DataFrame(DataSet.target, columns=['花の種類'])
DataSet_all = pd.concat([DataSet_data, DataSet_target], axis=1)
DataSet_all.head(10)

がく片の長さ  がく片の幅  花びらの長さ  はなびらの幅  花の種類
0     5.1    3.5     1.4     0.2     0
1     4.9    3.0     1.4     0.2     0
2     4.7    3.2     1.3     0.2     0
3     4.6    3.1     1.5     0.2     0
4     5.0    3.6     1.4     0.2     0
5     5.4    3.9     1.7     0.4     0
6     4.6    3.4     1.4     0.3     0
7     5.0    3.4     1.5     0.2     0
8     4.4    2.9     1.4     0.2     0
9     4.9    3.1     1.5     0.1     0