In [49]:
import cv2
import numpy as np
import pandas as pd
from glob import glob

In [50]:
# 相対パスを書くために、現在のディレクトリの位置を書き出す
import os
os.getcwd()


'd:\\My_programing\\python\\AI\\Training\\Net\\DataAugumentation'

In [51]:
# データを読み込むフォルダを指定する
DirPath = '../../../DataSet/AngleDetection/training/*'
#print(DirPath)

num_classes = 36
img_width, img_height = 64, 64

xs = []
ts = []
paths = []

for dir_path_1 in glob(DirPath):
    for dir_path_2 in glob(dir_path_1 + '/*'):
        for path in glob(dir_path_2 + '/*'):
            print(path, 'を読み込みました。')

            x = cv2.imread(path)
            x = cv2.resize(x, (img_width, img_height)).astype(np.float32)
            x /= 255.
            xs.append(x)

            t = float(dir_path_1[dir_path_1.find('\\'):].strip('\\'))
            ts.append(t)

otrusion\image4.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image40.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image41.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image44.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image45.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image46.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image47.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image48.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image49.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image5.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image50.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image51.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\protrusion\image52.jpg を読み込みました。
../../../DataSet/AngleDetection/training\95\pro

In [65]:
# listからnumpy配列を作成
xs = np.array(xs, dtype=np.float32)
ts = np.array(ts, dtype=np.int)


print('xs type = ', type(xs))
print('xs shape = ', xs.shape)
#print(xs)


print('ts type = ', type(ts))
print('ts shape = ', ts.shape)
print(ts)



xs type =  <class 'numpy.ndarray'>
xs shape =  (30694, 64, 64, 3)
ts type =  <class 'numpy.ndarray'>
ts shape =  (30694,)
[ 0  0  0 ... 95 95 95]


In [66]:
from keras.utils import np_utils

one_hot_ = np_utils.to_categorical(ts)
print(one_hot_)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [67]:
xs_2 = []
ts_2 = []
#paths = []

CLS = np.arange(0, 175, 5).astype('str')

for dir_path_1 in glob(DirPath):
    for dir_path_2 in glob(dir_path_1 + '/*'):
        for path in glob(dir_path_2 + '/*'):
            #print(path, 'を読み込みました。')

            x = cv2.imread(path)
            x = cv2.resize(x, (img_width, img_height)).astype(np.float32)
            x /= 255.
            xs_2.append(x)
            
            # one-hot-labelを作成する
            t = np.zeros(num_classes)
            p = dir_path_1[dir_path_1.find('\\'):].strip('\\')
            for i, cls in enumerate(CLS):
                if cls == p:
                    t[i] = 1

            ts_2.append(t)

xs_2 = np.array(xs_2, dtype=np.float32)
ts_2 = np.array(ts_2, dtype=np.int)

 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
34 95.0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [68]:
#print(xs_2)
print(ts_2)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# LeNetを作成する
## Network
from keras.models import Sequential, Model
from keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPool2D, Input, BatchNormalization

def LeNet():
    inputs = Input((img_height, img_width, 3))
    x = Conv2D(6, (5, 5), padding='valid', activation=None, name='conv1')(inputs)
    x = MaxPool2D((2, 2), padding='same')(x)
    x = Activation('sigmoid')(x)
    x = Conv2D(16, (5, 5), padding='vaild', activation=None, name='conv2')(x)
    x = MaxPool2D((2, 2), padding='same')(x)
    x = Activation('sigmoid')(x)

    x = Flatten()(x)
    x = Dense(120, name='dense1', activation=None)(x)
    x = Dense(64, name='dense2', activation=None)(x)
    x = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs=inputs, outputs=x, name='model')
    return model

In [69]:
# train
def train(DirPath):
    model = LeNet()

    for layer in model.layers:
        layer.trainable = True

    model.compile(
        loss = 'categorical_crossentropy',
        optimizer = keras.oprimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True),
        metrics=['accuracy'])
    
    xs, ts, paths = data_load(DirPath)

    # training
    mb = 8
    mbi = 0
    train_ind = np.arange(len(xs))
    np.random.seed(0)
    np.random.shuffle(train_ind)

    for i in range(500):
        if mbi + mb > len(xs):
            mb_ind = train_ind[mbi:]
            np.random.shuffule(train_ind)
            mb_ind = np.hstack((mb_ind, train_ind[:(mb-(len(xs)-mbi))]))
            mbi = mb - (len(xs) - mbi)
        else:
            mb_ind = train_ind[mbi: mbi+mb]
            mbi += mb

            print(mb_ind)